version: '3'

services:
  survey:
    build: helloFriend/photogallery
    depends_on:
      - 'database'
    ports:
      - '8080:8080'

  results:
    build: helloFriend/photogallery-postgres
    depends_on:
      - 'postgres'
    ports:
      - '3000:3000'
  database:
    image: postgres:latest
    ports:
      - '5432:5432'
      environment:
      - POSTGRES_DB=photogallery
      - POSTGRES_USER=helloFriend
    build: .