version: '3'

services:
  gallery:
    container_name: gallery
    restart: always
    build: .
    depends_on:
      - 'db'
    image: gallery
    ports:
      - '80:3001'
  db:
    image: postgres # use latest official postgres version
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=banana
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  pgdata: # named volumes can be managed easier using docker-compose